# coding: utf-8

"""
    CardPay REST API

    Welcome to the CardPay REST API. The CardPay API uses HTTP verbs and a [REST](https://en.wikipedia.org/wiki/Representational_state_transfer) resources endpoint structure (see more info about REST). Request and response payloads are formatted as JSON. Merchant uses API to create payments, refunds, payouts or recurrings, check or update transaction status and get information about created transactions. In API authentication process based on [OAuth 2.0](https://oauth.net/2/) standard. For recent changes see changelog section.  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from cardpay.model.flights import Flights  # noqa: F401,E501
from cardpay.model.item import Item  # noqa: F401,E501
from cardpay.model.shipping_address import ShippingAddress  # noqa: F401,E501


class PaymentRequestMerchantOrder(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        "description": "str",
        "digital_currency_type": "str",
        "expire_at": "datetime",
        "flights": "Flights",
        "id": "str",
        "items": "list[Item]",
        "shipping_address": "ShippingAddress",
    }

    attribute_map = {
        "description": "description",
        "digital_currency_type": "digital_currency_type",
        "expire_at": "expire_at",
        "flights": "flights",
        "id": "id",
        "items": "items",
        "shipping_address": "shipping_address",
    }

    def __init__(
        self,
        description=None,
        digital_currency_type=None,
        expire_at=None,
        flights=None,
        id=None,
        items=None,
        shipping_address=None,
    ):  # noqa: E501
        """PaymentRequestMerchantOrder - a model defined in Swagger"""  # noqa: E501

        self._description = None
        self._digital_currency_type = None
        self._expire_at = None
        self._flights = None
        self._id = None
        self._items = None
        self._shipping_address = None
        self.discriminator = None

        self.description = description
        if digital_currency_type is not None:
            self.digital_currency_type = digital_currency_type
        if expire_at is not None:
            self.expire_at = expire_at
        if flights is not None:
            self.flights = flights
        self.id = id
        if items is not None:
            self.items = items
        if shipping_address is not None:
            self.shipping_address = shipping_address

    @property
    def description(self):
        """Gets the description of this PaymentRequestMerchantOrder.  # noqa: E501

        Description of product/service being sold  # noqa: E501

        :return: The description of this PaymentRequestMerchantOrder.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this PaymentRequestMerchantOrder.

        Description of product/service being sold  # noqa: E501

        :param description: The description of this PaymentRequestMerchantOrder.  # noqa: E501
        :type: str
        """
        if description is None:
            raise ValueError(
                "Invalid value for `description`, must not be `None`"
            )  # noqa: E501
        if description is not None and len(description) > 200:
            raise ValueError(
                "Invalid value for `description`, length must be less than or equal to `200`"
            )  # noqa: E501
        if description is not None and len(description) < 1:
            raise ValueError(
                "Invalid value for `description`, length must be greater than or equal to `1`"
            )  # noqa: E501

        self._description = description

    class DigitalCurrencyType(object):
        CRYPTO_CURRENCY_TRANSACTION = "CRYPTO_CURRENCY_TRANSACTION"
        QUASI_CASH_TRANSACTION = "QUASI_CASH_TRANSACTION"
        CENTRAL_BANK_DIGITAL_CURRENCY_TRANSACTION = (
            "CENTRAL_BANK_DIGITAL_CURRENCY_TRANSACTION"
        )
        STABLECOIN_TRANSACTION = "STABLECOIN_TRANSACTION"
        BLOCKCHAIN_NATIVE_TOKEN_COIN_TRANSACTION = (
            "BLOCKCHAIN_NATIVE_TOKEN_COIN_TRANSACTION"
        )

    @property
    def digital_currency_type(self):
        """Gets the digital_currency_type of this PaymentRequestMerchantOrder.  # noqa: E501

        Type of digital currency or coin involved. Allowed values: 01 - Crypto currency transaction 02 - Quasi cash transaction 03 - Central Bank Digital Currency (CBDC) transaction 04 - Stablecoin transaction 05 - Blockchain Native Token/Coin transaction Required for digital currency transactions. The field is used if the card brand is Visa.  # noqa: E501

        :return: The digital_currency_type of this PaymentRequestMerchantOrder.  # noqa: E501
        :rtype: str
        """
        return self._digital_currency_type

    @digital_currency_type.setter
    def digital_currency_type(self, digital_currency_type):
        """Sets the digital_currency_type of this PaymentRequestMerchantOrder.

        Type of digital currency or coin involved. Allowed values: 01 - Crypto currency transaction 02 - Quasi cash transaction 03 - Central Bank Digital Currency (CBDC) transaction 04 - Stablecoin transaction 05 - Blockchain Native Token/Coin transaction Required for digital currency transactions. The field is used if the card brand is Visa.  # noqa: E501

        :param digital_currency_type: The digital_currency_type of this PaymentRequestMerchantOrder.  # noqa: E501
        :type: str
        """
        allowed_values = [
            "CRYPTO_CURRENCY_TRANSACTION",
            "QUASI_CASH_TRANSACTION",
            "CENTRAL_BANK_DIGITAL_CURRENCY_TRANSACTION",
            "STABLECOIN_TRANSACTION",
            "BLOCKCHAIN_NATIVE_TOKEN_COIN_TRANSACTION",
        ]  # noqa: E501
        if digital_currency_type not in allowed_values:
            raise ValueError(
                "Invalid value for `digital_currency_type` ({0}), must be one of {1}".format(  # noqa: E501
                    digital_currency_type, allowed_values
                )
            )

        self._digital_currency_type = digital_currency_type

    @property
    def expire_at(self):
        """Gets the expire_at of this PaymentRequestMerchantOrder.  # noqa: E501

        Payment expiration date and time in ISO 8601 format (example of format - yyyy-MM-dd'T'HH:mm:ss'Z') Should be UTC time.  Not all payment methods support this options, contact the Unlimit manager for details.  # noqa: E501

        :return: The expire_at of this PaymentRequestMerchantOrder.  # noqa: E501
        :rtype: datetime
        """
        return self._expire_at

    @expire_at.setter
    def expire_at(self, expire_at):
        """Sets the expire_at of this PaymentRequestMerchantOrder.

        Payment expiration date and time in ISO 8601 format (example of format - yyyy-MM-dd'T'HH:mm:ss'Z') Should be UTC time.  Not all payment methods support this options, contact the Unlimit manager for details.  # noqa: E501

        :param expire_at: The expire_at of this PaymentRequestMerchantOrder.  # noqa: E501
        :type: datetime
        """

        self._expire_at = expire_at

    @property
    def flights(self):
        """Gets the flights of this PaymentRequestMerchantOrder.  # noqa: E501

        Flights data *(for BANKCARD payment method only)*  # noqa: E501

        :return: The flights of this PaymentRequestMerchantOrder.  # noqa: E501
        :rtype: Flights
        """
        return self._flights

    @flights.setter
    def flights(self, flights):
        """Sets the flights of this PaymentRequestMerchantOrder.

        Flights data *(for BANKCARD payment method only)*  # noqa: E501

        :param flights: The flights of this PaymentRequestMerchantOrder.  # noqa: E501
        :type: Flights
        """

        self._flights = flights

    @property
    def id(self):
        """Gets the id of this PaymentRequestMerchantOrder.  # noqa: E501

        Order ID used by Merchant's shopping cart  # noqa: E501

        :return: The id of this PaymentRequestMerchantOrder.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this PaymentRequestMerchantOrder.

        Order ID used by Merchant's shopping cart  # noqa: E501

        :param id: The id of this PaymentRequestMerchantOrder.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501
        if id is not None and len(id) > 50:
            raise ValueError(
                "Invalid value for `id`, length must be less than or equal to `50`"
            )  # noqa: E501
        if id is not None and len(id) < 1:
            raise ValueError(
                "Invalid value for `id`, length must be greater than or equal to `1`"
            )  # noqa: E501

        self._id = id

    @property
    def items(self):
        """Gets the items of this PaymentRequestMerchantOrder.  # noqa: E501

        Array of items (in the shopping cart)  # noqa: E501

        :return: The items of this PaymentRequestMerchantOrder.  # noqa: E501
        :rtype: list[Item]
        """
        return self._items

    @items.setter
    def items(self, items):
        """Sets the items of this PaymentRequestMerchantOrder.

        Array of items (in the shopping cart)  # noqa: E501

        :param items: The items of this PaymentRequestMerchantOrder.  # noqa: E501
        :type: list[Item]
        """

        self._items = items

    @property
    def shipping_address(self):
        """Gets the shipping_address of this PaymentRequestMerchantOrder.  # noqa: E501

        Shipping Address  # noqa: E501

        :return: The shipping_address of this PaymentRequestMerchantOrder.  # noqa: E501
        :rtype: ShippingAddress
        """
        return self._shipping_address

    @shipping_address.setter
    def shipping_address(self, shipping_address):
        """Sets the shipping_address of this PaymentRequestMerchantOrder.

        Shipping Address  # noqa: E501

        :param shipping_address: The shipping_address of this PaymentRequestMerchantOrder.  # noqa: E501
        :type: ShippingAddress
        """

        self._shipping_address = shipping_address

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(
                    map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value)
                )
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict")
                        else item,
                        value.items(),
                    )
                )
            else:
                if value is not None:
                    result[attr] = value
        if issubclass(PaymentRequestMerchantOrder, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PaymentRequestMerchantOrder):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
